[versions]

kotlin = "1.6.10"
android_gradle = "7.1.1"
androidxCore = "1.7.0"
appcompat = "1.4.1"
material = "1.5.0"
lifecycle_viewmodel_ktx = "2.4.1"
coroutines = "1.5.2"
koin = "3.1.2"
room = "2.4.0"
constraintlayout = "2.1.1"
junit = "4.13.2"
mockito = "3.11.1"
core_testing = "2.1.0"
androidx_junit = "1.1.3"
swiperefreshlayout = "1.1.0"
mavericks = "2.6.0"

[libraries]

kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "android_gradle" }

androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }

lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle_viewmodel_ktx" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines"}
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines"}
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines"}

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin"}
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin"}

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room"}
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room"}
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room"}

junit = { module = "junit:junit", version.ref = "junit"}
mockito = { module = "org.mockito:mockito-inline", version.ref = "mockito"}
core-testing = { module = "androidx.arch.core:core-testing", version.ref = "core_testing"}
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx_junit"}

layout-constraint = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout"}
layout-swiperefresh = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout"}

mavericks = { module = "com.airbnb.android:mavericks", version.ref = "mavericks"}

[bundles]

android = [ "androidx-core", "appcompat", "material" ]
coroutines = [ "kotlinx-coroutines-core", "kotlinx-coroutines-android", "lifecycle-viewmodel-ktx" ]
room = [ "room-runtime", "room-ktx" ]
test = ["junit", "mockito", "core-testing" ]
